// Copyright 2018-19 PJ Engineering and Business Solutions Pty. Ltd. All rights reserved.

package elements

// Styles represent CSS3 attributes.
type Styles struct {
	AlignContent                string `react:"alignContent,omitempty"`
	AlignItems                  string `react:"alignItems,omitempty"`
	AlignSelf                   string `react:"alignSelf,omitempty"`
	AlignmentBaseline           string `react:"alignmentBaseline,omitempty"`
	All                         string `react:"all,omitempty"`
	Animation                   string `react:"animation,omitempty"`
	AnimationDelay              string `react:"animationDelay,omitempty"`
	AnimationDirection          string `react:"animationDirection,omitempty"`
	AnimationDuration           string `react:"animationDuration,omitempty"`
	AnimationFillMode           string `react:"animationFillMode,omitempty"`
	AnimationIterationCount     string `react:"animationIterationCount,omitempty"`
	AnimationName               string `react:"animationName,omitempty"`
	AnimationPlayState          string `react:"animationPlayState,omitempty"`
	AnimationTimingFunction     string `react:"animationTimingFunction,omitempty"`
	Appearance                  string `react:"appearance,omitempty"`
	BackfaceVisibility          string `react:"backfaceVisibility,omitempty"`
	Background                  string `react:"background,omitempty"`
	BackgroundAttachment        string `react:"backgroundAttachment,omitempty"`
	BackgroundClip              string `react:"backgroundClip,omitempty"`
	BackgroundColor             string `react:"backgroundColor,omitempty"`
	BackgroundImage             string `react:"backgroundImage,omitempty"`
	BackgroundOrigin            string `react:"backgroundOrigin,omitempty"`
	BackgroundPosition          string `react:"backgroundPosition,omitempty"`
	BackgroundRepeat            string `react:"backgroundRepeat,omitempty"`
	BackgroundSize              string `react:"backgroundSize,omitempty"`
	BaselineShift               string `react:"baselineShift,omitempty"`
	Binding                     string `react:"binding,omitempty"`
	Bleed                       string `react:"bleed,omitempty"`
	BookmarkLabel               string `react:"bookmarkLabel,omitempty"`
	BookmarkLevel               string `react:"bookmarkLevel,omitempty"`
	BookmarkState               string `react:"bookmarkState,omitempty"`
	Border                      string `react:"border,omitempty"`
	BorderBottom                string `react:"borderBottom,omitempty"`
	BorderBottomColor           string `react:"borderBottomColor,omitempty"`
	BorderBottomLeftRadius      string `react:"borderBottomLeftRadius,omitempty"`
	BorderBottomRightRadius     string `react:"borderBottomRightRadius,omitempty"`
	BorderBottomStyle           string `react:"borderBottomStyle,omitempty"`
	BorderBottomWidth           string `react:"borderBottomWidth,omitempty"`
	BorderBoundary              string `react:"borderBoundary,omitempty"`
	BorderCollapse              string `react:"borderCollapse,omitempty"`
	BorderColor                 string `react:"borderColor,omitempty"`
	BorderImage                 string `react:"borderImage,omitempty"`
	BorderImageOutset           string `react:"borderImageOutset,omitempty"`
	BorderImageRepeat           string `react:"borderImageRepeat,omitempty"`
	BorderImageSlice            string `react:"borderImageSlice,omitempty"`
	BorderImageSource           string `react:"borderImageSource,omitempty"`
	BorderImageWidth            string `react:"borderImageWidth,omitempty"`
	BorderLeft                  string `react:"borderLeft,omitempty"`
	BorderLeftColor             string `react:"borderLeftColor,omitempty"`
	BorderLeftStyle             string `react:"borderLeftStyle,omitempty"`
	BorderLeftWidth             string `react:"borderLeftWidth,omitempty"`
	BorderRadius                string `react:"borderRadius,omitempty"`
	BorderRight                 string `react:"borderRight,omitempty"`
	BorderRightColor            string `react:"borderRightColor,omitempty"`
	BorderRightStyle            string `react:"borderRightStyle,omitempty"`
	BorderRightWidth            string `react:"borderRightWidth,omitempty"`
	BorderSpacing               string `react:"borderSpacing,omitempty"`
	BorderStyle                 string `react:"borderStyle,omitempty"`
	BorderTop                   string `react:"borderTop,omitempty"`
	BorderTopColor              string `react:"borderTopColor,omitempty"`
	BorderTopLeftRadius         string `react:"borderTopLeftRadius,omitempty"`
	BorderTopRightRadius        string `react:"borderTopRightRadius,omitempty"`
	BorderTopStyle              string `react:"borderTopStyle,omitempty"`
	BorderTopWidth              string `react:"borderTopWidth,omitempty"`
	BorderWidth                 string `react:"borderWidth,omitempty"`
	Bottom                      string `react:"bottom,omitempty"`
	BoxDecorationBreak          string `react:"boxDecorationBreak,omitempty"`
	BoxShadow                   string `react:"boxShadow,omitempty"`
	BoxSizing                   string `react:"boxSizing,omitempty"`
	BoxSnap                     string `react:"boxSnap,omitempty"`
	BoxSuppress                 string `react:"boxSuppress,omitempty"`
	BreakAfter                  string `react:"breakAfter,omitempty"`
	BreakBefore                 string `react:"breakBefore,omitempty"`
	BreakInside                 string `react:"breakInside,omitempty"`
	CaptionSide                 string `react:"captionSide,omitempty"`
	Caret                       string `react:"caret,omitempty"`
	CaretShape                  string `react:"caretShape,omitempty"`
	Chains                      string `react:"chains,omitempty"`
	Clear                       string `react:"clear,omitempty"`
	ClipPath                    string `react:"clipPath,omitempty"`
	ClipRule                    string `react:"clipRule,omitempty"`
	Color                       string `react:"color,omitempty"`
	ColorInterpolationFilters   string `react:"colorInterpolationFilters,omitempty"`
	ColumnCount                 string `react:"columnCount,omitempty"`
	ColumnFill                  string `react:"columnFill,omitempty"`
	ColumnGap                   string `react:"columnGap,omitempty"`
	ColumnRule                  string `react:"columnRule,omitempty"`
	ColumnRuleColor             string `react:"columnRuleColor,omitempty"`
	ColumnRuleStyle             string `react:"columnRuleStyle,omitempty"`
	ColumnRuleWidth             string `react:"columnRuleWidth,omitempty"`
	ColumnSpan                  string `react:"columnSpan,omitempty"`
	ColumnWidth                 string `react:"columnWidth,omitempty"`
	Columns                     string `react:"columns,omitempty"`
	Contain                     string `react:"contain,omitempty"`
	Content                     string `react:"content,omitempty"`
	CounterIncrement            string `react:"counterIncrement,omitempty"`
	CounterReset                string `react:"counterReset,omitempty"`
	CounterSet                  string `react:"counterSet,omitempty"`
	Crop                        string `react:"crop,omitempty"`
	Cue                         string `react:"cue,omitempty"`
	CueAfter                    string `react:"cueAfter,omitempty"`
	CueBefore                   string `react:"cueBefore,omitempty"`
	Cursor                      string `react:"cursor,omitempty"`
	Direction                   string `react:"direction,omitempty"`
	Display                     string `react:"display,omitempty"`
	DisplayInside               string `react:"displayInside,omitempty"`
	DisplayList                 string `react:"displayList,omitempty"`
	DisplayOutside              string `react:"displayOutside,omitempty"`
	DominantBaseline            string `react:"dominantBaseline,omitempty"`
	EmptyCells                  string `react:"emptyCells,omitempty"`
	Filter                      string `react:"filter,omitempty"`
	Flex                        string `react:"flex,omitempty"`
	FlexBasis                   string `react:"flexBasis,omitempty"`
	FlexDirection               string `react:"flexDirection,omitempty"`
	FlexFlow                    string `react:"flexFlow,omitempty"`
	FlexGrow                    string `react:"flexGrow,omitempty"`
	FlexShrink                  string `react:"flexShrink,omitempty"`
	FlexWrap                    string `react:"flexWrap,omitempty"`
	Float                       string `react:"float,omitempty"`
	FloatOffset                 string `react:"floatOffset,omitempty"`
	FloodColor                  string `react:"floodColor,omitempty"`
	FloodOpacity                string `react:"floodOpacity,omitempty"`
	FlowFrom                    string `react:"flowFrom,omitempty"`
	FlowInto                    string `react:"flowInto,omitempty"`
	Font                        string `react:"font,omitempty"`
	FontFamily                  string `react:"fontFamily,omitempty"`
	FontFeatureSettings         string `react:"fontFeatureSettings,omitempty"`
	FontKerning                 string `react:"fontKerning,omitempty"`
	FontLanguageOverride        string `react:"fontLanguageOverride,omitempty"`
	FontMaxSize                 string `react:"fontMaxSize,omitempty"`
	FontMinSize                 string `react:"fontMinSize,omitempty"`
	FontOpticalSizing           string `react:"fontOpticalSizing,omitempty"`
	FontPalette                 string `react:"fontPalette,omitempty"`
	FontPresentation            string `react:"fontPresentation,omitempty"`
	FontSize                    string `react:"fontSize,omitempty"`
	FontSizeAdjust              string `react:"fontSizeAdjust,omitempty"`
	FontStretch                 string `react:"fontStretch,omitempty"`
	FontStyle                   string `react:"fontStyle,omitempty"`
	FontSynthesis               string `react:"fontSynthesis,omitempty"`
	FontVariant                 string `react:"fontVariant,omitempty"`
	FontVariantAlternates       string `react:"fontVariantAlternates,omitempty"`
	FontVariantCaps             string `react:"fontVariantCaps,omitempty"`
	FontVariantEastAsian        string `react:"fontVariantEastAsian,omitempty"`
	FontVariantLigatures        string `react:"fontVariantLigatures,omitempty"`
	FontVariantNumeric          string `react:"fontVariantNumeric,omitempty"`
	FontVariantPosition         string `react:"fontVariantPosition,omitempty"`
	FontVariationSettings       string `react:"fontVariationSettings,omitempty"`
	FontWeight                  string `react:"fontWeight,omitempty"`
	Grid                        string `react:"grid,omitempty"`
	GridArea                    string `react:"gridArea,omitempty"`
	GridAutoColumns             string `react:"gridAutoColumns,omitempty"`
	GridAutoFlow                string `react:"gridAutoFlow,omitempty"`
	GridAutoRows                string `react:"gridAutoRows,omitempty"`
	GridColumn                  string `react:"gridColumn,omitempty"`
	GridColumnEnd               string `react:"gridColumnEnd,omitempty"`
	GridColumnStart             string `react:"gridColumnStart,omitempty"`
	GridRow                     string `react:"gridRow,omitempty"`
	GridRowEnd                  string `react:"gridRowEnd,omitempty"`
	GridRowStart                string `react:"gridRowStart,omitempty"`
	GridTemplate                string `react:"gridTemplate,omitempty"`
	GridTemplateAreas           string `react:"gridTemplateAreas,omitempty"`
	GridTemplateColumns         string `react:"gridTemplateColumns,omitempty"`
	GridTemplateRows            string `react:"gridTemplateRows,omitempty"`
	HangingPunctuation          string `react:"hangingPunctuation,omitempty"`
	Height                      string `react:"height,omitempty"`
	Hyphens                     string `react:"hyphens,omitempty"`
	Icon                        string `react:"icon,omitempty"`
	ImageOrientation            string `react:"imageOrientation,omitempty"`
	ImageRendering              string `react:"imageRendering,omitempty"`
	ImageResolution             string `react:"imageResolution,omitempty"`
	ImeMode                     string `react:"imeMode,omitempty"`
	InitialLetters              string `react:"initialLetters,omitempty"`
	InitialLettersAlign         string `react:"initialLettersAlign,omitempty"`
	InitialLettersWrap          string `react:"initialLettersWrap,omitempty"`
	InlineSizing                string `react:"inlineSizing,omitempty"`
	JustifyContent              string `react:"justifyContent,omitempty"`
	JustifyItems                string `react:"justifyItems,omitempty"`
	JustifySelf                 string `react:"justifySelf,omitempty"`
	Left                        string `react:"left,omitempty"`
	LetterSpacing               string `react:"letterSpacing,omitempty"`
	LightingColor               string `react:"lightingColor,omitempty"`
	LineBreak                   string `react:"lineBreak,omitempty"`
	LineGrid                    string `react:"lineGrid,omitempty"`
	LineHeight                  string `react:"lineHeight,omitempty"`
	LineSnap                    string `react:"lineSnap,omitempty"`
	ListStyle                   string `react:"listStyle,omitempty"`
	ListStyleImage              string `react:"listStyleImage,omitempty"`
	ListStylePosition           string `react:"listStylePosition,omitempty"`
	ListStyleType               string `react:"listStyleType,omitempty"`
	Margin                      string `react:"margin,omitempty"`
	MarginBottom                string `react:"marginBottom,omitempty"`
	MarginLeft                  string `react:"marginLeft,omitempty"`
	MarginRight                 string `react:"marginRight,omitempty"`
	MarginTop                   string `react:"marginTop,omitempty"`
	MarkerSide                  string `react:"markerSide,omitempty"`
	Marks                       string `react:"marks,omitempty"`
	Mask                        string `react:"mask,omitempty"`
	MaskBox                     string `react:"maskBox,omitempty"`
	MaskBoxOutset               string `react:"maskBoxOutset,omitempty"`
	MaskBoxRepeat               string `react:"maskBoxRepeat,omitempty"`
	MaskBoxSlice                string `react:"maskBoxSlice,omitempty"`
	MaskBoxSource               string `react:"maskBoxSource,omitempty"`
	MaskBoxWidth                string `react:"maskBoxWidth,omitempty"`
	MaskClip                    string `react:"maskClip,omitempty"`
	MaskImage                   string `react:"maskImage,omitempty"`
	MaskOrigin                  string `react:"maskOrigin,omitempty"`
	MaskPosition                string `react:"maskPosition,omitempty"`
	MaskRepeat                  string `react:"maskRepeat,omitempty"`
	MaskSize                    string `react:"maskSize,omitempty"`
	MaskSourceType              string `react:"maskSourceType,omitempty"`
	MaskType                    string `react:"maskType,omitempty"`
	MaxHeight                   string `react:"maxHeight,omitempty"`
	MaxLines                    string `react:"maxLines,omitempty"`
	MaxWidth                    string `react:"maxWidth,omitempty"`
	MinHeight                   string `react:"minHeight,omitempty"`
	MinWidth                    string `react:"minWidth,omitempty"`
	MoveTo                      string `react:"moveTo,omitempty"`
	NavDown                     string `react:"navDown,omitempty"`
	NavIndex                    string `react:"navIndex,omitempty"`
	NavLeft                     string `react:"navLeft,omitempty"`
	NavRight                    string `react:"navRight,omitempty"`
	NavUp                       string `react:"navUp,omitempty"`
	ObjectFit                   string `react:"objectFit,omitempty"`
	ObjectPosition              string `react:"objectPosition,omitempty"`
	Opacity                     string `react:"opacity,omitempty"`
	Order                       string `react:"order,omitempty"`
	Orphans                     string `react:"orphans,omitempty"`
	Outline                     string `react:"outline,omitempty"`
	OutlineColor                string `react:"outlineColor,omitempty"`
	OutlineOffset               string `react:"outlineOffset,omitempty"`
	OutlineStyle                string `react:"outlineStyle,omitempty"`
	OutlineWidth                string `react:"outlineWidth,omitempty"`
	Overflow                    string `react:"overflow,omitempty"`
	OverflowWrap                string `react:"overflowWrap,omitempty"`
	OverflowX                   string `react:"overflowX,omitempty"`
	OverflowY                   string `react:"overflowY,omitempty"`
	Padding                     string `react:"padding,omitempty"`
	PaddingBottom               string `react:"paddingBottom,omitempty"`
	PaddingLeft                 string `react:"paddingLeft,omitempty"`
	PaddingRight                string `react:"paddingRight,omitempty"`
	PaddingTop                  string `react:"paddingTop,omitempty"`
	Page                        string `react:"page,omitempty"`
	PageBreakAfter              string `react:"pageBreakAfter,omitempty"`
	PageBreakBefore             string `react:"pageBreakBefore,omitempty"`
	PageBreakInside             string `react:"pageBreakInside,omitempty"`
	PagePolicy                  string `react:"pagePolicy,omitempty"`
	Pause                       string `react:"pause,omitempty"`
	PauseAfter                  string `react:"pauseAfter,omitempty"`
	PauseBefore                 string `react:"pauseBefore,omitempty"`
	Perspective                 string `react:"perspective,omitempty"`
	PerspectiveOrigin           string `react:"perspectiveOrigin,omitempty"`
	PolarAnchor                 string `react:"polarAnchor,omitempty"`
	PolarAngle                  string `react:"polarAngle,omitempty"`
	PolarDistance               string `react:"polarDistance,omitempty"`
	PolarOrigin                 string `react:"polarOrigin,omitempty"`
	Position                    string `react:"position,omitempty"`
	PresentationLevel           string `react:"presentationLevel,omitempty"`
	Quotes                      string `react:"quotes,omitempty"`
	RegionFragment              string `react:"regionFragment,omitempty"`
	Resize                      string `react:"resize,omitempty"`
	Rest                        string `react:"rest,omitempty"`
	RestAfter                   string `react:"restAfter,omitempty"`
	RestBefore                  string `react:"restBefore,omitempty"`
	Right                       string `react:"right,omitempty"`
	Rotation                    string `react:"rotation,omitempty"`
	RotationPoint               string `react:"rotationPoint,omitempty"`
	RowGap                      string `react:"rowGap,omitempty"`
	RubyAlign                   string `react:"rubyAlign,omitempty"`
	RubyMerge                   string `react:"rubyMerge,omitempty"`
	RubyPosition                string `react:"rubyPosition,omitempty"`
	ScrollPadding               string `react:"scrollPadding,omitempty"`
	ScrollPaddingBlock          string `react:"scrollPaddingBlock,omitempty"`
	ScrollPaddingBlockEnd       string `react:"scrollPaddingBlockEnd,omitempty"`
	ScrollPaddingBlockStart     string `react:"scrollPaddingBlockStart,omitempty"`
	ScrollPaddingBottom         string `react:"scrollPaddingBottom,omitempty"`
	ScrollPaddingInline         string `react:"scrollPaddingInline,omitempty"`
	ScrollPaddingInlineEnd      string `react:"scrollPaddingInlineEnd,omitempty"`
	ScrollPaddingInlineStart    string `react:"scrollPaddingInlineStart,omitempty"`
	ScrollPaddingLeft           string `react:"scrollPaddingLeft,omitempty"`
	ScrollPaddingRight          string `react:"scrollPaddingRight,omitempty"`
	ScrollPaddingTop            string `react:"scrollPaddingTop,omitempty"`
	ScrollSnapAlign             string `react:"scrollSnapAlign,omitempty"`
	ScrollSnapMargin            string `react:"scrollSnapMargin,omitempty"`
	ScrollSnapMarginBlock       string `react:"scrollSnapMarginBlock,omitempty"`
	ScrollSnapMarginBlockEnd    string `react:"scrollSnapMarginBlockEnd,omitempty"`
	ScrollSnapMarginBlockStart  string `react:"scrollSnapMarginBlockStart,omitempty"`
	ScrollSnapMarginBottom      string `react:"scrollSnapMarginBottom,omitempty"`
	ScrollSnapMarginInline      string `react:"scrollSnapMarginInline,omitempty"`
	ScrollSnapMarginInlineEnd   string `react:"scrollSnapMarginInlineEnd,omitempty"`
	ScrollSnapMarginInlineStart string `react:"scrollSnapMarginInlineStart,omitempty"`
	ScrollSnapMarginLeft        string `react:"scrollSnapMarginLeft,omitempty"`
	ScrollSnapMarginRight       string `react:"scrollSnapMarginRight,omitempty"`
	ScrollSnapMarginTop         string `react:"scrollSnapMarginTop,omitempty"`
	ScrollSnapStop              string `react:"scrollSnapStop,omitempty"`
	ScrollSnapType              string `react:"scrollSnapType,omitempty"`
	ShapeImageThreshold         string `react:"shapeImageThreshold,omitempty"`
	ShapeInside                 string `react:"shapeInside,omitempty"`
	ShapeOutside                string `react:"shapeOutside,omitempty"`
	ShapeMargin                 string `react:"shapeMargin,omitempty"`
	Size                        string `react:"size,omitempty"`
	Speak                       string `react:"speak,omitempty"`
	SpeakAs                     string `react:"speakAs,omitempty"`
	StringSet                   string `react:"stringSet,omitempty"`
	TabSize                     string `react:"tabSize,omitempty"`
	TableLayout                 string `react:"tableLayout,omitempty"`
	TextAlign                   string `react:"textAlign,omitempty"`
	TextAlignLast               string `react:"textAlignLast,omitempty"`
	TextCombineUpright          string `react:"textCombineUpright,omitempty"`
	TextDecoration              string `react:"textDecoration,omitempty"`
	TextDecorationColor         string `react:"textDecorationColor,omitempty"`
	TextDecorationLine          string `react:"textDecorationLine,omitempty"`
	TextDecorationSkip          string `react:"textDecorationSkip,omitempty"`
	TextDecorationStyle         string `react:"textDecorationStyle,omitempty"`
	TextEmphasis                string `react:"textEmphasis,omitempty"`
	TextEmphasisColor           string `react:"textEmphasisColor,omitempty"`
	TextEmphasisPosition        string `react:"textEmphasisPosition,omitempty"`
	TextEmphasisStyle           string `react:"textEmphasisStyle,omitempty"`
	TextIndent                  string `react:"textIndent,omitempty"`
	TextJustify                 string `react:"textJustify,omitempty"`
	TextOrientation             string `react:"textOrientation,omitempty"`
	TextOverflow                string `react:"textOverflow,omitempty"`
	TextShadow                  string `react:"textShadow,omitempty"`
	TextSpaceCollapse           string `react:"textSpaceCollapse,omitempty"`
	TextTransform               string `react:"textTransform,omitempty"`
	TextUnderlinePosition       string `react:"textUnderlinePosition,omitempty"`
	TextWrap                    string `react:"textWrap,omitempty"`
	TouchAction                 string `react:"touchAction,omitempty"`
	Top                         string `react:"top,omitempty"`
	Transform                   string `react:"transform,omitempty"`
	TransformOrigin             string `react:"transformOrigin,omitempty"`
	TransformStyle              string `react:"transformStyle,omitempty"`
	Transition                  string `react:"transition,omitempty"`
	TransitionDelay             string `react:"transitionDelay,omitempty"`
	TransitionDuration          string `react:"transitionDuration,omitempty"`
	TransitionProperty          string `react:"transitionProperty,omitempty"`
	TransitionTimingFunction    string `react:"transitionTimingFunction,omitempty"`
	UnicodeBidi                 string `react:"unicodeBidi,omitempty"`
	UserSelect                  string `react:"userSelect,omitempty"`
	VerticalAlign               string `react:"verticalAlign,omitempty"`
	Visibility                  string `react:"visibility,omitempty"`
	VoiceBalance                string `react:"voiceBalance,omitempty"`
	VoiceDuration               string `react:"voiceDuration,omitempty"`
	VoiceFamily                 string `react:"voiceFamily,omitempty"`
	VoicePitch                  string `react:"voicePitch,omitempty"`
	VoiceRange                  string `react:"voiceRange,omitempty"`
	VoiceRate                   string `react:"voiceRate,omitempty"`
	VoiceStress                 string `react:"voiceStress,omitempty"`
	VoiceVolume                 string `react:"voiceVolume,omitempty"`
	WhiteSpace                  string `react:"whiteSpace,omitempty"`
	Widows                      string `react:"widows,omitempty"`
	Width                       string `react:"width,omitempty"`
	WillChange                  string `react:"willChange,omitempty"`
	WordBreak                   string `react:"wordBreak,omitempty"`
	WordSpacing                 string `react:"wordSpacing,omitempty"`
	WordWrap                    string `react:"wordWrap,omitempty"`
	WrapFlow                    string `react:"wrapFlow,omitempty"`
	WrapThrough                 string `react:"wrapThrough,omitempty"`
	WritingMode                 string `react:"writingMode,omitempty"`
	ZIndex                      string `react:"zIndex,omitempty"`
}
